# What is PyTorch?


## Tensors

In [1]:
from __future__ import print_function
import torch
x= torch.Tensor(5,3)
print(x)


 0.0000e+00  0.0000e+00 -2.9979e+12
 4.5729e-41 -2.9977e+12  4.5729e-41
 1.5290e-38  0.0000e+00  1.5290e-38
 0.0000e+00  1.5290e-38  0.0000e+00
 1.5290e-38  0.0000e+00  0.0000e+00
[torch.FloatTensor of size 5x3]



In [2]:
x=torch.rand(5,3)
print(x)


 0.5898  0.0650  0.7898
 0.2219  0.2771  0.1420
 0.7125  0.5196  0.5242
 0.5142  0.0046  0.1350
 0.7366  0.2603  0.8073
[torch.FloatTensor of size 5x3]



In [8]:
print(x.size())

torch.Size([5, 3])


## Operation

In [9]:
# addition : syntax 1
y= torch.rand(5,3)
print(x+y)


 1.2415  1.3718  1.5770
 1.6846  1.1516  1.9227
 0.5702  1.7914  0.4597
 0.9089  0.2793  0.9646
 0.4560  0.7771  1.3784
[torch.FloatTensor of size 5x3]



In [11]:
# addition : syntax 2
print(torch.add(x,y))


 1.2415  1.3718  1.5770
 1.6846  1.1516  1.9227
 0.5702  1.7914  0.4597
 0.9089  0.2793  0.9646
 0.4560  0.7771  1.3784
[torch.FloatTensor of size 5x3]



In [12]:
# Addition  giving output tensor
result = torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)


 1.2415  1.3718  1.5770
 1.6846  1.1516  1.9227
 0.5702  1.7914  0.4597
 0.9089  0.2793  0.9646
 0.4560  0.7771  1.3784
[torch.FloatTensor of size 5x3]



In [13]:
# Addition : in-place
# adds x to y
y.add_(x)
print(y)


 1.2415  1.3718  1.5770
 1.6846  1.1516  1.9227
 0.5702  1.7914  0.4597
 0.9089  0.2793  0.9646
 0.4560  0.7771  1.3784
[torch.FloatTensor of size 5x3]



In [14]:
print(x[:,1])


 0.6235
 0.7765
 0.9846
 0.0187
 0.7598
[torch.FloatTensor of size 5]



## Numpy bridge

In [16]:
a=torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [17]:
b=a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [18]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


## Converting numpy Array to torch Tensor

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

