# What is PyTorch?


## Tensors

In [1]:
from __future__ import print_function
import torch
x= torch.Tensor(5,3)
print(x)


1.00000e-38 *
  0.0000  0.0000 -0.5691
  0.0046 -0.5692  0.0046
  1.5294  0.0000  1.5294
  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x3]



In [2]:
x=torch.rand(5,3)
print(x)


 0.3497  0.9370  0.5683
 0.7252  0.8995  0.1877
 0.9069  0.4848  0.1512
 0.1969  0.6690  0.1592
 0.3947  0.5862  0.9110
[torch.FloatTensor of size 5x3]



In [3]:
print(x.size())

torch.Size([5, 3])


## Operation

In [4]:
# addition : syntax 1
y= torch.rand(5,3)
print(x+y)


 0.8447  1.1793  0.8697
 1.2010  1.2879  0.6870
 0.9599  1.2362  0.3007
 0.7191  1.1287  0.5256
 0.4676  0.6468  1.8140
[torch.FloatTensor of size 5x3]



In [5]:
# addition : syntax 2
print(torch.add(x,y))


 0.8447  1.1793  0.8697
 1.2010  1.2879  0.6870
 0.9599  1.2362  0.3007
 0.7191  1.1287  0.5256
 0.4676  0.6468  1.8140
[torch.FloatTensor of size 5x3]



In [6]:
# Addition  giving output tensor
result = torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)


 0.8447  1.1793  0.8697
 1.2010  1.2879  0.6870
 0.9599  1.2362  0.3007
 0.7191  1.1287  0.5256
 0.4676  0.6468  1.8140
[torch.FloatTensor of size 5x3]



In [7]:
# Addition : in-place
# adds x to y
y.add_(x)
print(y)


 0.8447  1.1793  0.8697
 1.2010  1.2879  0.6870
 0.9599  1.2362  0.3007
 0.7191  1.1287  0.5256
 0.4676  0.6468  1.8140
[torch.FloatTensor of size 5x3]



In [8]:
print(x[:,1])


 0.9370
 0.8995
 0.4848
 0.6690
 0.5862
[torch.FloatTensor of size 5]



## Numpy bridge

In [9]:
a=torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [10]:
b=a.numpy()
print(b)

[ 1.  1.  1.  1.  1.]


In [11]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[ 2.  2.  2.  2.  2.]


## Converting numpy Array to torch Tensor

In [12]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]

