Tensors

In [11]:
from __future__ import print_function
import torch

In [7]:
torch.Tensor(5,3)

tensor([[ 3.6510e+18,  4.5736e-41,  3.6510e+18],
        [ 4.5736e-41,  0.0000e+00,  0.0000e+00],
        [ 7.0065e-45,         nan,  3.6749e-14],
        [ 3.0628e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  7.0065e-45]])

In [18]:
torch.empty(2,4)

tensor([[ 3.6510e+18,  4.5736e-41,  3.6510e+18,  4.5736e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [17]:
torch.rand(7,3)

tensor([[ 0.9648,  0.1087,  0.9380],
        [ 0.4838,  0.0573,  0.8607],
        [ 0.0833,  0.4350,  0.3045],
        [ 0.7813,  0.4151,  0.6097],
        [ 0.2077,  0.7770,  0.6446],
        [ 0.2598,  0.5794,  0.7230],
        [ 0.3830,  0.9144,  0.2177]])

In [76]:
x=torch.rand(6,3)
print(x.size())

torch.Size([6, 3])


## Operation

In [77]:
# addition : syntax 1
y= torch.rand(6,3)
print(x)
print(y)
print(x+y)

tensor([[ 0.5055,  0.1052,  0.9486],
        [ 0.5004,  0.2223,  0.4238],
        [ 0.3482,  0.5997,  0.1659],
        [ 0.3423,  0.2767,  0.4403],
        [ 0.9228,  0.3183,  0.0609],
        [ 0.9452,  0.4546,  0.0323]])
tensor([[ 0.8320,  0.0795,  0.0648],
        [ 0.7606,  0.7300,  0.7351],
        [ 0.3759,  0.9941,  0.1419],
        [ 0.9519,  0.6483,  0.3618],
        [ 0.7699,  0.7917,  0.9777],
        [ 0.2064,  0.4712,  0.4711]])
tensor([[ 1.3375,  0.1846,  1.0134],
        [ 1.2610,  0.9524,  1.1589],
        [ 0.7241,  1.5939,  0.3078],
        [ 1.2942,  0.9250,  0.8021],
        [ 1.6927,  1.1100,  1.0386],
        [ 1.1516,  0.9259,  0.5034]])


In [25]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0],
        [ 0,  0,  0]])

In [26]:
torch.tensor([5.5, 3])

tensor([ 5.5000,  3.0000])

In [83]:
# addition : syntax 2
print(torch.add(x,y))

tensor([[ 1.3375,  0.1846,  1.0134],
        [ 1.2610,  0.9524,  1.1589],
        [ 0.7241,  1.5939,  0.3078],
        [ 1.2942,  0.9250,  0.8021],
        [ 1.6927,  1.1100,  1.0386],
        [ 1.1516,  0.9259,  0.5034]])


In [98]:
# Addition  giving output tensor
result = torch.Tensor(6,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.3375,  0.1846,  1.0134],
        [ 1.2610,  0.9524,  1.1589],
        [ 0.7241,  1.5939,  0.3078],
        [ 1.2942,  0.9250,  0.8021],
        [ 1.6927,  1.1100,  1.0386],
        [ 1.1516,  0.9259,  0.5034]])


In [99]:
# Addition : in-place
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.3375,  0.1846,  1.0134],
        [ 1.2610,  0.9524,  1.1589],
        [ 0.7241,  1.5939,  0.3078],
        [ 1.2942,  0.9250,  0.8021],
        [ 1.6927,  1.1100,  1.0386],
        [ 1.1516,  0.9259,  0.5034]])


In [100]:
print(x[:,1])

tensor([ 0.1052,  0.2223,  0.5997,  0.2767,  0.3183,  0.4546])


In [109]:
x = torch.randn(4, 4)
print(x, x.size())
print(x.view(8,2))
y = x.view(16)
print(y, y.size())
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z, z.size())

tensor([[ 0.0919, -0.1341, -0.0204,  0.7917],
        [-0.2265,  1.7513,  1.3092, -0.1232],
        [-0.2903,  1.8177,  0.7712, -0.3176],
        [-0.0890,  1.5849, -1.4962,  0.8540]]) torch.Size([4, 4])
tensor([[ 0.0919, -0.1341],
        [-0.0204,  0.7917],
        [-0.2265,  1.7513],
        [ 1.3092, -0.1232],
        [-0.2903,  1.8177],
        [ 0.7712, -0.3176],
        [-0.0890,  1.5849],
        [-1.4962,  0.8540]])
tensor([ 0.0919, -0.1341, -0.0204,  0.7917, -0.2265,  1.7513,  1.3092,
        -0.1232, -0.2903,  1.8177,  0.7712, -0.3176, -0.0890,  1.5849,
        -1.4962,  0.8540]) torch.Size([16])
tensor([[ 0.0919, -0.1341, -0.0204,  0.7917, -0.2265,  1.7513,  1.3092,
         -0.1232],
        [-0.2903,  1.8177,  0.7712, -0.3176, -0.0890,  1.5849, -1.4962,
          0.8540]]) torch.Size([2, 8])


## Numpy bridge

In [30]:
a=torch.ones(5)
print(a)

tensor([ 1.,  1.,  1.,  1.,  1.])


In [31]:
b=a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [50]:
a.add_(1)
print(a)
print(b)

tensor([ 21.,  21.,  21.,  21.,  21.])
[21. 21. 21. 21. 21.]


 Converting numpy Array to torch Tensor

In [70]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)


[1. 1. 1. 1. 1.]
tensor([ 1.,  1.,  1.,  1.,  1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]


CUDA Tensor

In [72]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` object to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))

tensor([[ 1.7780,  1.4390,  1.9605],
        [ 1.9273,  1.2835,  1.9752],
        [ 1.8358,  1.7912,  1.3349],
        [ 1.5105,  1.3113,  1.0491],
        [ 1.6217,  1.1210,  1.0081],
        [ 1.0735,  1.2404,  1.2173]], device='cuda:0')
tensor([[ 1.7780,  1.4390,  1.9605],
        [ 1.9273,  1.2835,  1.9752],
        [ 1.8358,  1.7912,  1.3349],
        [ 1.5105,  1.3113,  1.0491],
        [ 1.6217,  1.1210,  1.0081],
        [ 1.0735,  1.2404,  1.2173]], dtype=torch.float64)
